### ISSUE TITLE
object x, y offsets

### ISSUE THREAD

**Issue by intermet** [Daweyy/MapRenderer-DR#1]
Hi!
I was wondering about the json file https://cdn.dofusretro.fr/img/maps-gfx//object/object.json.
The sprites can be found easily in the files `clips/o*.swf`. But what about the offsets x, y, that are used to properly place the objects over the cells?
I am currently trying to improve and complete the features. 
Thanks!

**Comment by ghost** [comment]
Hello,
These data are extracted with [Jeff](https://github.com/H3r3zy/Jeff)
They can be accessed directly in each sprite's data, here's an example with [JPEXS](https://github.com/jindrapetrik/jpexs-decompiler) : ![image](https://github.com/ShowMeDawey/MapRenderer-DR/assets/899316/8dfe1609-7b33-4c5e-af38-48eb9ed78750)
The project (and this data) haven't been updated for a while though
I hope that one day we'll be able to generate beautiful renderings for every maps in the game 😄

**Comment by intermet** [comment]
Thanks! I understand now more the Flash Movie clip structure. The thing is that in Flash, shapes are coded in vector graphics (not png). I guess we should ultimately use the svg and not the png. I was able to implement code the rotations. I obtain pretty good results :
![10172_12_-26](https://github.com/ShowMeDawey/MapRenderer-DR/assets/6547743/070cfca8-e764-4f92-bade-844a6f4b6924)
![165_8_-2](https://github.com/ShowMeDawey/MapRenderer-DR/assets/6547743/e90bcfe7-c96d-4f9f-b26f-4d0718d4bf6b)


There is one thing that I cannot figure out: some maps seem to have multiple background, even if only one is provided in the swf file of the map. For example:

![10166_12_-22](https://github.com/ShowMeDawey/MapRenderer-DR/assets/6547743/f2ca85a4-3cb2-46d5-87d5-c7152f2fab8e)
or
![1195_11_17](https://github.com/ShowMeDawey/MapRenderer-DR/assets/6547743/9e166854-4ecb-46aa-b579-7941633a8033)
I cannot find in the loader source code where those backgrounds are loaded.

**Comment by ghost** [comment]
For these 2 examples, it's actually a problem with Jeff exporting empty sprites (didn't got root cause yet)
There's always only one background per map on Dofus 1
I haven't tried SVG because (as far as I know) there's no tool for exporting **correctly** in this format (not satisfied with JPEXS about it)

About rotations, I think we had something already, but feel free to open a PR if you got better results 😄 (I know it's wasn't fully handled)
